"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()
TESTING = 'test' in sys.argv

# Caminho base usado para banco, arquivos estaticos e uploads.
BASE_DIR = Path(__file__).resolve().parent.parent


# Valores sensiveis e modo de execucao vem do arquivo .env.
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]

# Protecoes de producao ficam desligadas localmente e sao ativadas por variaveis de ambiente.
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT') == 'True'
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE') == 'True'
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE') == 'True'
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS') == 'True'
SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD') == 'True'


# Apps do Django e app principal da barbearia.

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'agendamentos.apps.AgendamentosConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'agendamentos.observability.RequestObservabilityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'agendamentos.middleware.TenantMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'agendamentos.input_safety.InputSafetyMiddleware',
    'agendamentos.middleware.TermsAcceptanceMiddleware',
    'agendamentos.middleware.ActiveUserSessionMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if not TESTING:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'agendamentos.context_processors.configuracao_global',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# SQLite permanece como fallback local; produção recebe a URL completa do
# Supabase/Pooler sem armazenar credenciais no repositório.
DATABASE_URL = os.getenv('DATABASE_URL', '').strip()
if DATABASE_URL:
    import dj_database_url

    database_is_postgres = DATABASE_URL.lower().startswith(('postgres://', 'postgresql://'))
    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=int(os.getenv('DB_CONN_MAX_AGE', '60')),
            conn_health_checks=True,
            ssl_require=(
                database_is_postgres
                and os.getenv('DB_SSL_REQUIRE', 'True') == 'True'
            ),
        )
    }
    if database_is_postgres and os.getenv('DB_DISABLE_PREPARED_STATEMENTS', 'False') == 'True':
        DATABASES['default'].setdefault('OPTIONS', {})['prepare_threshold'] = None
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Validadores padrao do Django para senhas dos usuarios do painel.

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Datas e horarios seguem o fuso da barbearia no Brasil.

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Arquivos estaticos do front-end e uploads enviados pelo painel.
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

static_backend = (
    'django.contrib.staticfiles.storage.StaticFilesStorage'
    if DEBUG or TESTING
    else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
)

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': static_backend,
    },
}
WHITENOISE_MANIFEST_STRICT = False

# Supabase Storage expõe uma interface compatível com S3. O bucket configurado
# aqui deve conter somente imagens públicas de branding e profissionais.
if os.getenv('AWS_STORAGE_BUCKET_NAME'):
    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {
            'access_key': os.getenv('AWS_ACCESS_KEY_ID'),
            'secret_key': os.getenv('AWS_SECRET_ACCESS_KEY'),
            'bucket_name': os.getenv('AWS_STORAGE_BUCKET_NAME'),
            'endpoint_url': os.getenv('AWS_S3_ENDPOINT_URL'),
            'region_name': os.getenv('AWS_S3_REGION_NAME', 'us-east-1'),
            'addressing_style': 'path',
            'default_acl': None,
            'file_overwrite': False,
            'querystring_auth': False,
            'location': 'media',
        },
    }

# Fluxo de autenticacao usado pela area interna dos barbeiros.
LOGIN_URL = '/painel/login/'
LOGIN_REDIRECT_URL = 'painel_home'
LOGOUT_REDIRECT_URL = 'index'

SESSION_COOKIE_AGE = int(os.getenv('SESSION_COOKIE_AGE', '86400'))
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Render termina TLS no proxy e encaminha o protocolo original neste header.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
CSRF_TRUSTED_ORIGINS = [
    origem.strip()
    for origem in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origem.strip()
]

REDIS_URL = os.getenv('REDIS_URL', '')
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'barbearia-cache',
        }
    }

PUBLIC_CACHE_TIMEOUT = int(os.getenv('PUBLIC_CACHE_TIMEOUT', '60'))

# Documentos internos. Alterar qualquer versão força um novo aceite dos membros.
TERMS_VERSION = os.getenv('TERMS_VERSION', '1.0')
PRIVACY_POLICY_VERSION = os.getenv('PRIVACY_POLICY_VERSION', '1.0')

# Limites configuráveis para superfícies sensíveis ou que geram custo externo.
LOGIN_RATE_LIMIT_IP = int(os.getenv('LOGIN_RATE_LIMIT_IP', '10'))
LOGIN_RATE_LIMIT_USERNAME = int(os.getenv('LOGIN_RATE_LIMIT_USERNAME', '5'))
LOGIN_RATE_LIMIT_WINDOW = int(os.getenv('LOGIN_RATE_LIMIT_WINDOW', '900'))
GEMINI_RATE_LIMIT_USER = int(os.getenv('GEMINI_RATE_LIMIT_USER', '10'))
GEMINI_RATE_LIMIT_WINDOW = int(os.getenv('GEMINI_RATE_LIMIT_WINDOW', '60'))

# Evita que uploads ou formulários grandes consumam toda a memória do worker.
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('DATA_UPLOAD_MAX_MEMORY_SIZE', str(40 * 1024 * 1024)))
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv('FILE_UPLOAD_MAX_MEMORY_SIZE', str(8 * 1024 * 1024)))
TENANT_BACKUP_MAX_BYTES = int(os.getenv('TENANT_BACKUP_MAX_BYTES', str(25 * 1024 * 1024)))
TENANT_BACKUP_UPLOAD_MAX_BYTES = int(os.getenv('TENANT_BACKUP_UPLOAD_MAX_BYTES', str(40 * 1024 * 1024)))
TENANT_BACKUP_MAX_RECORDS = int(os.getenv('TENANT_BACKUP_MAX_RECORDS', '100000'))

# O tenant é resolvido por ``slug.TENANT_BASE_DOMAIN``. Em desenvolvimento,
# a queda para a única empresa cadastrada preserva URLs como localhost:8000.
TENANT_BASE_DOMAIN = os.getenv('TENANT_BASE_DOMAIN', 'localhost')
TENANT_ALLOW_SINGLE_FALLBACK = os.getenv('TENANT_ALLOW_SINGLE_FALLBACK', 'True') == 'True'
TENANT_RESERVED_SUBDOMAINS = {
    item.strip().lower()
    for item in os.getenv('TENANT_RESERVED_SUBDOMAINS', 'www,admin,app').split(',')
    if item.strip()
}

# Um unico insight por empresa e periodo. ``daily`` reseta na virada local do dia;
# ``weekly`` toda segunda; ``monthly`` no primeiro dia do mes seguinte.
GEMINI_INSIGHTS_PERIOD = os.getenv('GEMINI_INSIGHTS_PERIOD', 'daily').lower()
if GEMINI_INSIGHTS_PERIOD not in {'daily', 'weekly', 'monthly'}:
    GEMINI_INSIGHTS_PERIOD = 'daily'
GEMINI_INSIGHTS_CACHE_TIMEOUT = int(os.getenv('GEMINI_INSIGHTS_CACHE_TIMEOUT', '2764800'))

# Observabilidade. Queries ficam ligadas em execucao real e desligadas somente
# durante a suite para evitar milhares de linhas sem valor diagnostico.
QUERY_LOGGING_ENABLED = os.getenv(
    'QUERY_LOGGING_ENABLED',
    'False' if TESTING else 'True',
) == 'True'
ALERT_SLOW_REQUEST_MS = int(os.getenv('ALERT_SLOW_REQUEST_MS', '2000'))
ALERT_ERROR_RATE_PERCENT = float(os.getenv('ALERT_ERROR_RATE_PERCENT', '5'))
ALERT_CPU_PERCENT = float(os.getenv('ALERT_CPU_PERCENT', '90'))
ALERT_MEMORY_MB = int(os.getenv('ALERT_MEMORY_MB', '512'))

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'safe_json': {
            '()': 'agendamentos.observability.SafeJsonFormatter',
        },
    },
    'handlers': {
        'console_json': {
            'class': 'logging.StreamHandler',
            'formatter': 'safe_json',
        },
    },
    'root': {
        'handlers': ['console_json'],
        'level': os.getenv('LOG_LEVEL', 'CRITICAL' if TESTING else 'INFO'),
    },
    'loggers': {
        'django': {
            'handlers': ['console_json'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'CRITICAL' if TESTING else 'INFO'),
            'propagate': False,
        },
        'agendamentos': {
            'handlers': ['console_json'],
            'level': os.getenv('APP_LOG_LEVEL', 'CRITICAL' if TESTING else 'INFO'),
            'propagate': False,
        },
    },
}
